/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jagguz_wrld (https://sketchfab.com/jagathkrishna148)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rolls-royce-ghost-a45a10b1225644739475f8dd541f8875
Title: Rolls Royce Ghost
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    polySurface88_car_glass_0: THREE.Mesh
    polySurface89_car_glass_0: THREE.Mesh
    polySurface90_car_glass_0: THREE.Mesh
    polySurface91_car_glass_0: THREE.Mesh
    polySurface92_car_glass_0: THREE.Mesh
    polySurface93_car_glass_0: THREE.Mesh
    polySurface94_car_glass_0: THREE.Mesh
    polySurface95_car_glass_0: THREE.Mesh
    polySurface114_seat_0: THREE.Mesh
    polySurface144_interior_front_switch_0: THREE.Mesh
    polySurface147_seat_0: THREE.Mesh
    polySurface480_interior_car_under_white_carpet_0: THREE.Mesh
    polySurface480_interior_under_black_0: THREE.Mesh
    polySurface481_interior_back_black_0: THREE.Mesh
    polySurface479_interior_car_under_white_carpet_0: THREE.Mesh
    polySurface159_interior_under_plus_0: THREE.Mesh
    polySurface160_interior_under_plus_0: THREE.Mesh
    polySurface165_seat_0: THREE.Mesh
    polySurface172_interior_box_black1_0: THREE.Mesh
    polySurface172_interior_box_white_0: THREE.Mesh
    polySurface172_interior_box_black_0: THREE.Mesh
    polySurface173_inter_seat_under_0: THREE.Mesh
    polySurface174_inter_seat_under_0: THREE.Mesh
    polySurface175_interior_car_side_wall_0: THREE.Mesh
    polySurface175_interior_car_back_wall_0: THREE.Mesh
    polySurface448_interior_car__screen_0: THREE.Mesh
    polySurface450_interior_car__screen_0: THREE.Mesh
    polySurface572_interior_car_stearing_2_0: THREE.Mesh
    polySurface241_interior_car_stearing_3_0: THREE.Mesh
    polySurface245_interior_car_steaing_suporter_0: THREE.Mesh
    polySurface246_interior_hand_brake_0: THREE.Mesh
    polySurface247_interior_hand_brake_0: THREE.Mesh
    polySurface248_interior_hand_brake_0: THREE.Mesh
    polySurface262_inter_seat_under_0: THREE.Mesh
    polySurface263_inter_seat_under_0: THREE.Mesh
    polySurface264_inter_seat_under_0: THREE.Mesh
    polySurface266_inter_seat_under_0: THREE.Mesh
    polySurface267_inter_seat_under_0: THREE.Mesh
    polySurface268_inter_seat_under_0: THREE.Mesh
    polySurface269_inter_seat_under_0: THREE.Mesh
    polySurface461_interior_white_dash_board_0: THREE.Mesh
    polySurface461_interior_dash_board_black_0: THREE.Mesh
    polySurface280_interior_black_clock_0: THREE.Mesh
    polySurface280_interior_clock_0: THREE.Mesh
    polySurface366_car_bottom_0: THREE.Mesh
    polySurface390_front_small_blacks_0: THREE.Mesh
    polySurface466_interior_car_side_wall_0: THREE.Mesh
    polySurface466_interior_car_back_wall_0: THREE.Mesh
    polySurface242_interior_car_steaing_suporter_0: THREE.Mesh
    polySurface205_seat_0: THREE.Mesh
    polySurface235_seat_0: THREE.Mesh
    polySurface191_seat_0: THREE.Mesh
    polySurface185_seat_0: THREE.Mesh
    polySurface397_caw_tyre_0: THREE.Mesh
    polySurface467_caw_tyre_0: THREE.Mesh
    polySurface468_caw_tyre_0: THREE.Mesh
    polySurface469_caw_tyre_0: THREE.Mesh
    polySurface244_car_stearing_1_0: THREE.Mesh
    CAR_BODY_Car_Paint_0: THREE.Mesh
    CAR_BODY_Car_Paint_0_1: THREE.Mesh
    CAR_BODY_Car_Paint_0_2: THREE.Mesh
    polySurface567_car_body333_0: THREE.Mesh
    polySurface568_Stainless_Steel_0: THREE.Mesh
    polySurface569_car_body333_0: THREE.Mesh
    polySurface570_Car_Paint_0: THREE.Mesh
    polySurface571_Car_Paint_0: THREE.Mesh
    polySurface109_car_side_window_black_0: THREE.Mesh
    polySurface108_Stainless_Steel_0: THREE.Mesh
    polySurface375_interior_glass_rim_0: THREE.Mesh
    polySurface485_Stainless_Steel_0: THREE.Mesh
    polySurface486_Stainless_Steel_0: THREE.Mesh
    polySurface496_Stainless_Steel_0: THREE.Mesh
    polySurface497_Stainless_Steel_0: THREE.Mesh
    polySurface498_Stainless_Steel_0: THREE.Mesh
    polySurface499_Stainless_Steel_0: THREE.Mesh
    polySurface500_Stainless_Steel_0: THREE.Mesh
    polySurface501_Stainless_Steel_0: THREE.Mesh
    polySurface502_outterior_metal_0: THREE.Mesh
    polySurface503_Stainless_Steel_0: THREE.Mesh
    polySurface504_outterior_metal_0: THREE.Mesh
    polySurface505_Stainless_Steel_0: THREE.Mesh
    polySurface506_outterior_metal_0: THREE.Mesh
    polySurface574_Stainless_Steel_0: THREE.Mesh
    polySurface511_Stainless_Steel_0: THREE.Mesh
    polySurface521_Stainless_Steel_0: THREE.Mesh
    polySurface522_Stainless_Steel_0: THREE.Mesh
    polySurface523_Stainless_Steel_0: THREE.Mesh
    polySurface524_outterior_metal_0: THREE.Mesh
    polySurface525_Stainless_Steel_0: THREE.Mesh
    polySurface526_Stainless_Steel_0: THREE.Mesh
    polySurface527_Stainless_Steel_0: THREE.Mesh
    polySurface528_Stainless_Steel_0: THREE.Mesh
    polySurface529_Stainless_Steel_0: THREE.Mesh
    polySurface530_outterior_metal_0: THREE.Mesh
    polySurface531_Stainless_Steel_0: THREE.Mesh
    polySurface532_Stainless_Steel_0: THREE.Mesh
    polySurface534_Stainless_Steel_0: THREE.Mesh
    polySurface535_outterior_metal_0: THREE.Mesh
    polySurface536_outterior_metal_0: THREE.Mesh
    polySurface544_Stainless_Steel_0: THREE.Mesh
    polySurface555_Stainless_Steel_0: THREE.Mesh
    polySurface112_interior_back_window_black_0: THREE.Mesh
    polySurface391_car_front_small_wind_grill_0: THREE.Mesh
    polySurface138_interior_metal_ring_0: THREE.Mesh
    polySurface138_interior_blue_light_0: THREE.Mesh
    polySurface218_interior_srean_under_platic_0: THREE.Mesh
    polySurface218_interior_scren_stant_metal_0: THREE.Mesh
    polySurface327_brake_small_0: THREE.Mesh
    polySurface362_srew_brake_0: THREE.Mesh
    polySurface457_interior_metal_ring_0: THREE.Mesh
    polySurface457_interior_blue_light_0: THREE.Mesh
    polySurface459_interior_mettal_switch_0: THREE.Mesh
    polySurface161_interior_music_box_0: THREE.Mesh
    pasted__polySurface77_interior_texture_dash_board_0: THREE.Mesh
    pasted__polySurface79_interior_texture_dash_board_0: THREE.Mesh
    polySurface463_interior_switch_0: THREE.Mesh
    polySurface121_interior_doow_bag_0: THREE.Mesh
    polySurface121_interior_door_black_0: THREE.Mesh
    polySurface121_interior_box__blackk_0: THREE.Mesh
    polySurface134_interior_door_switch_0: THREE.Mesh
    pPipe1_interior_switchh_0: THREE.Mesh
    polySurface145_mirror_12_0: THREE.Mesh
    polySurface456_polySurface278Shape_interior_metal1_0: THREE.Mesh
    polySurface291_grill_0: THREE.Mesh
    polySurface477_digital_meeter_0: THREE.Mesh
    polySurface96_light_0: THREE.Mesh
    polySurface482_mirror_12_0: THREE.Mesh
    polySurface483_interior__miroor_0: THREE.Mesh
    polySurface556_car_brakee_0: THREE.Mesh
    polySurface557_car_brakee_0: THREE.Mesh
    polySurface558_car_brakee_0: THREE.Mesh
    polySurface559_car_brakee_0: THREE.Mesh
    polySurface586_weel_r_0: THREE.Mesh
    polySurface587_weel_r_0: THREE.Mesh
    pCube8_under_the_car_2_box_0: THREE.Mesh
    pCylinder31_under_car_wwe_0: THREE.Mesh
    pasted__polySurface58_Car_Paint_0: THREE.Mesh
    pasted__polySurface80_Car_Paint_0: THREE.Mesh
    pCube14_interior_cover_grill_0: THREE.Mesh
    pCube15_interior_cover_grill_0: THREE.Mesh
    polySurface576_logo_0: THREE.Mesh
    polySurface577_logo_0: THREE.Mesh
    polySurface578_logo_0: THREE.Mesh
    polySurface579_logo_0: THREE.Mesh
    polySurface580_logo_0: THREE.Mesh
    polySurface581_logo_0: THREE.Mesh
    polySurface582_logo_0: THREE.Mesh
    polySurface583_logo_0: THREE.Mesh
    polySurface584_logo_0: THREE.Mesh
    polySurface585_logo_0: THREE.Mesh
    polySurface487_Stainless_Steel_0: THREE.Mesh
    pCube18_phong82_0: THREE.Mesh
  }
  materials: {
    car_glass: THREE.MeshStandardMaterial
    seat: THREE.MeshStandardMaterial
    interior_front_switch: THREE.MeshStandardMaterial
    interior_car_under_white_carpet: THREE.MeshStandardMaterial
    interior_under_black: THREE.MeshStandardMaterial
    interior_back_black: THREE.MeshStandardMaterial
    interior_under_plus: THREE.MeshStandardMaterial
    interior_box_black1: THREE.MeshStandardMaterial
    interior_box_white: THREE.MeshStandardMaterial
    interior_box_black: THREE.MeshStandardMaterial
    inter_seat_under: THREE.MeshStandardMaterial
    interior_car_side_wall: THREE.MeshStandardMaterial
    interior_car_back_wall: THREE.MeshStandardMaterial
    interior_car__screen: THREE.MeshPhysicalMaterial
    interior_car_stearing_2: THREE.MeshStandardMaterial
    interior_car_stearing_3: THREE.MeshStandardMaterial
    interior_car_steaing_suporter: THREE.MeshStandardMaterial
    interior_hand_brake: THREE.MeshStandardMaterial
    interior_white_dash_board: THREE.MeshStandardMaterial
    interior_dash_board_black: THREE.MeshStandardMaterial
    interior_black_clock: THREE.MeshStandardMaterial
    interior_clock: THREE.MeshStandardMaterial
    car_bottom: THREE.MeshStandardMaterial
    front_small_blacks: THREE.MeshStandardMaterial
    caw_tyre: THREE.MeshStandardMaterial
    car_stearing_1: THREE.MeshStandardMaterial
    Car_Paint: THREE.MeshPhysicalMaterial
    car_body333: THREE.MeshStandardMaterial
    Stainless_Steel: THREE.MeshPhysicalMaterial
    car_side_window_black: THREE.MeshStandardMaterial
    interior_glass_rim: THREE.MeshStandardMaterial
    outterior_metal: THREE.MeshPhysicalMaterial
    interior_back_window_black: THREE.MeshStandardMaterial
    car_front_small_wind_grill: THREE.MeshStandardMaterial
    interior_metal_ring: THREE.MeshStandardMaterial
    interior_blue_light: THREE.MeshStandardMaterial
    interior_srean_under_platic: THREE.MeshStandardMaterial
    interior_scren_stant_metal: THREE.MeshStandardMaterial
    brake_small: THREE.MeshStandardMaterial
    srew_brake: THREE.MeshStandardMaterial
    interior_mettal_switch: THREE.MeshStandardMaterial
    interior_music_box: THREE.MeshStandardMaterial
    interior_texture_dash_board: THREE.MeshStandardMaterial
    interior_switch: THREE.MeshStandardMaterial
    interior_doow_bag: THREE.MeshStandardMaterial
    interior_door_black: THREE.MeshStandardMaterial
    interior_box__blackk: THREE.MeshStandardMaterial
    interior_door_switch: THREE.MeshStandardMaterial
    interior_switchh: THREE.MeshStandardMaterial
    mirror_12: THREE.MeshStandardMaterial
    interior_metal1: THREE.MeshStandardMaterial
    grill: THREE.MeshStandardMaterial
    digital_meeter: THREE.MeshStandardMaterial
    light: THREE.MeshStandardMaterial
    interior__miroor: THREE.MeshStandardMaterial
    car_brakee: THREE.MeshStandardMaterial
    weel_r: THREE.MeshStandardMaterial
    under_the_car_2_box: THREE.MeshStandardMaterial
    under_car_wwe: THREE.MeshStandardMaterial
    interior_cover_grill: THREE.MeshStandardMaterial
    logo: THREE.MeshStandardMaterial
    phong82: THREE.MeshStandardMaterial
  }
}

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/rolls.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      PolySurfacecarglass: nodes.polySurface88_car_glass_0,
      PolySurfacecarglass1: nodes.polySurface89_car_glass_0,
      PolySurfacecarglass2: nodes.polySurface90_car_glass_0,
      PolySurfacecarglass3: nodes.polySurface91_car_glass_0,
      PolySurfacecarglass4: nodes.polySurface92_car_glass_0,
      PolySurfacecarglass5: nodes.polySurface93_car_glass_0,
      PolySurfacecarglass6: nodes.polySurface94_car_glass_0,
      PolySurfacecarglass7: nodes.polySurface95_car_glass_0,
      PolySurfaceseat: nodes.polySurface114_seat_0,
      PolySurfaceinteriorfrontswitch: nodes.polySurface144_interior_front_switch_0,
      PolySurfaceseat1: nodes.polySurface147_seat_0,
      PolySurfaceinteriorcarunderwhitecarpet:
        nodes.polySurface480_interior_car_under_white_carpet_0,
      PolySurfaceinteriorunderblack: nodes.polySurface480_interior_under_black_0,
      PolySurfaceinteriorbackblack: nodes.polySurface481_interior_back_black_0,
      PolySurfaceinteriorcarunderwhitecarpet1:
        nodes.polySurface479_interior_car_under_white_carpet_0,
      PolySurfaceinteriorunderplus: nodes.polySurface159_interior_under_plus_0,
      PolySurfaceinteriorunderplus1: nodes.polySurface160_interior_under_plus_0,
      PolySurfaceseat2: nodes.polySurface165_seat_0,
      PolySurfaceinteriorboxblack: nodes.polySurface172_interior_box_black1_0,
      PolySurfaceinteriorboxwhite: nodes.polySurface172_interior_box_white_0,
      PolySurfaceinteriorboxblack1: nodes.polySurface172_interior_box_black_0,
      PolySurfaceinterseatunder: nodes.polySurface173_inter_seat_under_0,
      PolySurfaceinterseatunder1: nodes.polySurface174_inter_seat_under_0,
      PolySurfaceinteriorcarsidewall: nodes.polySurface175_interior_car_side_wall_0,
      PolySurfaceinteriorcarbackwall: nodes.polySurface175_interior_car_back_wall_0,
      PolySurfaceinteriorcarscreen: nodes.polySurface448_interior_car__screen_0,
      PolySurfaceinteriorcarscreen1: nodes.polySurface450_interior_car__screen_0,
      PolySurfaceinteriorcarstearing: nodes.polySurface572_interior_car_stearing_2_0,
      PolySurfaceinteriorcarstearing1: nodes.polySurface241_interior_car_stearing_3_0,
      PolySurfaceinteriorcarsteaingsuporter: nodes.polySurface245_interior_car_steaing_suporter_0,
      PolySurfaceinteriorhandbrake: nodes.polySurface246_interior_hand_brake_0,
      PolySurfaceinteriorhandbrake1: nodes.polySurface247_interior_hand_brake_0,
      PolySurfaceinteriorhandbrake2: nodes.polySurface248_interior_hand_brake_0,
      PolySurfaceinterseatunder2: nodes.polySurface262_inter_seat_under_0,
      PolySurfaceinterseatunder3: nodes.polySurface263_inter_seat_under_0,
      PolySurfaceinterseatunder4: nodes.polySurface264_inter_seat_under_0,
      PolySurfaceinterseatunder5: nodes.polySurface266_inter_seat_under_0,
      PolySurfaceinterseatunder6: nodes.polySurface267_inter_seat_under_0,
      PolySurfaceinterseatunder7: nodes.polySurface268_inter_seat_under_0,
      PolySurfaceinterseatunder8: nodes.polySurface269_inter_seat_under_0,
      PolySurfaceinteriorwhitedashboard: nodes.polySurface461_interior_white_dash_board_0,
      PolySurfaceinteriordashboardblack: nodes.polySurface461_interior_dash_board_black_0,
      PolySurfaceinteriorblackclock: nodes.polySurface280_interior_black_clock_0,
      PolySurfaceinteriorclock: nodes.polySurface280_interior_clock_0,
      PolySurfacecarbottom: nodes.polySurface366_car_bottom_0,
      PolySurfacefrontsmallblacks: nodes.polySurface390_front_small_blacks_0,
      PolySurfaceinteriorcarsidewall1: nodes.polySurface466_interior_car_side_wall_0,
      PolySurfaceinteriorcarbackwall1: nodes.polySurface466_interior_car_back_wall_0,
      PolySurfaceinteriorcarsteaingsuporter1: nodes.polySurface242_interior_car_steaing_suporter_0,
      PolySurfaceseat3: nodes.polySurface205_seat_0,
      PolySurfaceseat4: nodes.polySurface235_seat_0,
      PolySurfaceseat5: nodes.polySurface191_seat_0,
      PolySurfaceseat6: nodes.polySurface185_seat_0,
      PolySurfacecawtyre: nodes.polySurface397_caw_tyre_0,
      PolySurfacecawtyre1: nodes.polySurface467_caw_tyre_0,
      PolySurfacecawtyre2: nodes.polySurface468_caw_tyre_0,
      PolySurfacecawtyre3: nodes.polySurface469_caw_tyre_0,
      PolySurfacecarstearing: nodes.polySurface244_car_stearing_1_0,
      CARBODYCarPaint: nodes.CAR_BODY_Car_Paint_0,
      CARBODYCarPaint1: nodes.CAR_BODY_Car_Paint_0_1,
      CARBODYCarPaint2: nodes.CAR_BODY_Car_Paint_0_2,
      PolySurfacecarbody: nodes.polySurface567_car_body333_0,
      PolySurfaceStainlessSteel: nodes.polySurface568_Stainless_Steel_0,
      PolySurfacecarbody1: nodes.polySurface569_car_body333_0,
      PolySurfaceCarPaint: nodes.polySurface570_Car_Paint_0,
      PolySurfaceCarPaint1: nodes.polySurface571_Car_Paint_0,
      PolySurfacecarsidewindowblack: nodes.polySurface109_car_side_window_black_0,
      PolySurfaceStainlessSteel1: nodes.polySurface108_Stainless_Steel_0,
      PolySurfaceinteriorglassrim: nodes.polySurface375_interior_glass_rim_0,
      PolySurfaceStainlessSteel2: nodes.polySurface485_Stainless_Steel_0,
      PolySurfaceStainlessSteel3: nodes.polySurface486_Stainless_Steel_0,
      PolySurfaceStainlessSteel4: nodes.polySurface496_Stainless_Steel_0,
      PolySurfaceStainlessSteel5: nodes.polySurface497_Stainless_Steel_0,
      PolySurfaceStainlessSteel6: nodes.polySurface498_Stainless_Steel_0,
      PolySurfaceStainlessSteel7: nodes.polySurface499_Stainless_Steel_0,
      PolySurfaceStainlessSteel8: nodes.polySurface500_Stainless_Steel_0,
      PolySurfaceStainlessSteel9: nodes.polySurface501_Stainless_Steel_0,
      PolySurfaceoutteriormetal: nodes.polySurface502_outterior_metal_0,
      PolySurfaceStainlessSteel10: nodes.polySurface503_Stainless_Steel_0,
      PolySurfaceoutteriormetal1: nodes.polySurface504_outterior_metal_0,
      PolySurfaceStainlessSteel11: nodes.polySurface505_Stainless_Steel_0,
      PolySurfaceoutteriormetal2: nodes.polySurface506_outterior_metal_0,
      PolySurfaceStainlessSteel12: nodes.polySurface574_Stainless_Steel_0,
      PolySurfaceStainlessSteel13: nodes.polySurface511_Stainless_Steel_0,
      PolySurfaceStainlessSteel14: nodes.polySurface521_Stainless_Steel_0,
      PolySurfaceStainlessSteel15: nodes.polySurface522_Stainless_Steel_0,
      PolySurfaceStainlessSteel16: nodes.polySurface523_Stainless_Steel_0,
      PolySurfaceoutteriormetal3: nodes.polySurface524_outterior_metal_0,
      PolySurfaceStainlessSteel17: nodes.polySurface525_Stainless_Steel_0,
      PolySurfaceStainlessSteel18: nodes.polySurface526_Stainless_Steel_0,
      PolySurfaceStainlessSteel19: nodes.polySurface527_Stainless_Steel_0,
      PolySurfaceStainlessSteel20: nodes.polySurface528_Stainless_Steel_0,
      PolySurfaceStainlessSteel21: nodes.polySurface529_Stainless_Steel_0,
      PolySurfaceoutteriormetal4: nodes.polySurface530_outterior_metal_0,
      PolySurfaceStainlessSteel22: nodes.polySurface531_Stainless_Steel_0,
      PolySurfaceStainlessSteel23: nodes.polySurface532_Stainless_Steel_0,
      PolySurfaceStainlessSteel24: nodes.polySurface534_Stainless_Steel_0,
      PolySurfaceoutteriormetal5: nodes.polySurface535_outterior_metal_0,
      PolySurfaceoutteriormetal6: nodes.polySurface536_outterior_metal_0,
      PolySurfaceStainlessSteel25: nodes.polySurface544_Stainless_Steel_0,
      PolySurfaceStainlessSteel26: nodes.polySurface555_Stainless_Steel_0,
      PolySurfaceinteriorbackwindowblack: nodes.polySurface112_interior_back_window_black_0,
      PolySurfacecarfrontsmallwindgrill: nodes.polySurface391_car_front_small_wind_grill_0,
      PolySurfaceinteriormetalring: nodes.polySurface138_interior_metal_ring_0,
      PolySurfaceinteriorbluelight: nodes.polySurface138_interior_blue_light_0,
      PolySurfaceinteriorsreanunderplatic: nodes.polySurface218_interior_srean_under_platic_0,
      PolySurfaceinteriorscrenstantmetal: nodes.polySurface218_interior_scren_stant_metal_0,
      PolySurfacebrakesmall: nodes.polySurface327_brake_small_0,
      PolySurfacesrewbrake: nodes.polySurface362_srew_brake_0,
      PolySurfaceinteriormetalring1: nodes.polySurface457_interior_metal_ring_0,
      PolySurfaceinteriorbluelight1: nodes.polySurface457_interior_blue_light_0,
      PolySurfaceinteriormettalswitch: nodes.polySurface459_interior_mettal_switch_0,
      PolySurfaceinteriormusicbox: nodes.polySurface161_interior_music_box_0,
      PastedpolySurfaceinteriortexturedashboard:
        nodes.pasted__polySurface77_interior_texture_dash_board_0,
      PastedpolySurfaceinteriortexturedashboard1:
        nodes.pasted__polySurface79_interior_texture_dash_board_0,
      PolySurfaceinteriorswitch: nodes.polySurface463_interior_switch_0,
      PolySurfaceinteriordoowbag: nodes.polySurface121_interior_doow_bag_0,
      PolySurfaceinteriordoorblack: nodes.polySurface121_interior_door_black_0,
      PolySurfaceinteriorboxblackk: nodes.polySurface121_interior_box__blackk_0,
      PolySurfaceinteriordoorswitch: nodes.polySurface134_interior_door_switch_0,
      PPipeinteriorswitchh: nodes.pPipe1_interior_switchh_0,
      PolySurfacemirror: nodes.polySurface145_mirror_12_0,
      PolySurfacepolySurfaceShapeinteriormetal:
        nodes.polySurface456_polySurface278Shape_interior_metal1_0,
      PolySurfacegrill: nodes.polySurface291_grill_0,
      PolySurfacedigitalmeeter: nodes.polySurface477_digital_meeter_0,
      PolySurfacelight: nodes.polySurface96_light_0,
      PolySurfacemirror1: nodes.polySurface482_mirror_12_0,
      PolySurfaceinteriormiroor: nodes.polySurface483_interior__miroor_0,
      PolySurfacecarbrakee: nodes.polySurface556_car_brakee_0,
      PolySurfacecarbrakee1: nodes.polySurface557_car_brakee_0,
      PolySurfacecarbrakee2: nodes.polySurface558_car_brakee_0,
      PolySurfacecarbrakee3: nodes.polySurface559_car_brakee_0,
      PolySurfaceweelr: nodes.polySurface586_weel_r_0,
      PolySurfaceweelr1: nodes.polySurface587_weel_r_0,
      PCubeunderthecarbox: nodes.pCube8_under_the_car_2_box_0,
      PCylinderundercarwwe: nodes.pCylinder31_under_car_wwe_0,
      PastedpolySurfaceCarPaint: nodes.pasted__polySurface58_Car_Paint_0,
      PastedpolySurfaceCarPaint1: nodes.pasted__polySurface80_Car_Paint_0,
      PCubeinteriorcovergrill: nodes.pCube14_interior_cover_grill_0,
      PCubeinteriorcovergrill1: nodes.pCube15_interior_cover_grill_0,
      PolySurfacelogo: nodes.polySurface576_logo_0,
      PolySurfacelogo1: nodes.polySurface577_logo_0,
      PolySurfacelogo2: nodes.polySurface578_logo_0,
      PolySurfacelogo3: nodes.polySurface579_logo_0,
      PolySurfacelogo4: nodes.polySurface580_logo_0,
      PolySurfacelogo5: nodes.polySurface581_logo_0,
      PolySurfacelogo6: nodes.polySurface582_logo_0,
      PolySurfacelogo7: nodes.polySurface583_logo_0,
      PolySurfacelogo8: nodes.polySurface584_logo_0,
      PolySurfacelogo9: nodes.polySurface585_logo_0,
      PolySurfaceStainlessSteel27: nodes.polySurface487_Stainless_Steel_0,
      PCubephong: nodes.pCube18_phong82_0,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}>
            <instances.PolySurfaceinteriorcarunderwhitecarpet />
            <instances.PolySurfaceinteriorunderblack />
          </group>
          <group
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}>
            <instances.PolySurfaceinteriorboxblack />
            <instances.PolySurfaceinteriorboxwhite />
            <instances.PolySurfaceinteriorboxblack1 />
          </group>
          <group
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}>
            <instances.PolySurfaceinteriorcarsidewall />
            <instances.PolySurfaceinteriorcarbackwall />
          </group>
          <group
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}>
            <instances.PolySurfaceinteriorwhitedashboard />
            <instances.PolySurfaceinteriordashboardblack />
          </group>
          <group
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}>
            <instances.PolySurfaceinteriorblackclock />
            <instances.PolySurfaceinteriorclock />
          </group>
          <group
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}>
            <instances.PolySurfaceinteriorcarsidewall1 />
            <instances.PolySurfaceinteriorcarbackwall1 />
          </group>
          <group position={[1.332, -0.43, -2.401]} rotation={[-Math.PI / 2, 0, 0]} scale={6112.408}>
            <instances.CARBODYCarPaint />
            <instances.CARBODYCarPaint1 />
            <instances.CARBODYCarPaint2 />
          </group>
          <group position={[1.332, -0.43, -2.401]} rotation={[-Math.PI / 2, 0, 0]} scale={6112.408}>
            <instances.PolySurfaceinteriormetalring />
            <instances.PolySurfaceinteriorbluelight />
          </group>
          <group position={[1.332, -0.43, -2.401]} rotation={[-Math.PI / 2, 0, 0]} scale={6112.408}>
            <instances.PolySurfaceinteriorsreanunderplatic />
            <instances.PolySurfaceinteriorscrenstantmetal />
          </group>
          <group
            position={[1.333, -16.618, -75.252]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={4761.595}>
            <instances.PolySurfaceinteriormetalring1 />
            <instances.PolySurfaceinteriorbluelight1 />
          </group>
          <group position={[1.332, -0.43, -2.401]} rotation={[-Math.PI / 2, 0, 0]} scale={6112.408}>
            <instances.PolySurfaceinteriordoowbag />
            <instances.PolySurfaceinteriordoorblack />
            <instances.PolySurfaceinteriorboxblackk />
          </group>
          <instances.PolySurfacecarglass
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass2
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass3
            position={[0.626, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass4
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass5
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass6
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarglass7
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorfrontswitch
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorbackblack
            position={[1.332, 77.484, -2.361]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarunderwhitecarpet1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorunderplus
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorunderplus1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat2
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarscreen
            position={[1.332, 77.484, -2.353]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarscreen1
            position={[1.332, 77.484, -2.084]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarstearing
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarstearing1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarsteaingsuporter
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorhandbrake
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorhandbrake1
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorhandbrake2
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder2
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder3
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder4
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder5
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder6
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder7
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinterseatunder8
            position={[1.332, 77.484, -3.782]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbottom
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacefrontsmallblacks
            position={[1.332, 77.484, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorcarsteaingsuporter1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat3
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat4
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat5
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceseat6
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecawtyre
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecawtyre1
            position={[1.332, -0.532, -324.651]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecawtyre2
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[-6112.408, 6112.408, 6112.408]}
          />
          <instances.PolySurfacecawtyre3
            position={[1.332, -0.43, -324.552]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[-6112.408, 6112.408, 6112.408]}
          />
          <instances.PolySurfacecarstearing
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbody
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbody1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceCarPaint
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceCarPaint1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarsidewindowblack
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriorglassrim
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel2
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel3
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel4
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel5
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel6
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel7
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel8
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel9
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal
            position={[1.332, -55.352, -30.846]}
            rotation={[-1.337, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel10
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel11
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal2
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel12
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel13
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel14
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel15
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel16
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal3
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel17
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel18
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel19
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel20
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel21
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal4
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel22
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel23
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel24
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal5
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceoutteriormetal6
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel25
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel26
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[-6112.408, 6112.408, 6112.408]}
          />
          <instances.PolySurfaceinteriorbackwindowblack
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarfrontsmallwindgrill
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacebrakesmall
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacesrewbrake
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriormettalswitch
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriormusicbox
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PastedpolySurfaceinteriortexturedashboard
            position={[1.311, 94.893, 247.676]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-2527.155, 2605.444, 2605.444]}
          />
          <instances.PastedpolySurfaceinteriortexturedashboard1
            position={[1.243, 94.928, 248.448]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-2527.155, 2605.444, 2605.444]}
          />
          <instances.PolySurfaceinteriorswitch
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriordoorswitch
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PPipeinteriorswitchh
            position={[1.248, 50.12, 64.645]}
            rotation={[-Math.PI / 2, 0, -2.996]}
            scale={[580.965, 580.965, 105.952]}
          />
          <instances.PolySurfacemirror
            position={[1.801, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacepolySurfaceShapeinteriormetal
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacegrill
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacedigitalmeeter
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelight
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacemirror1
            position={[1.332, -0.43, -2.488]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceinteriormiroor
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbrakee
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbrakee1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbrakee2
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacecarbrakee3
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfaceweelr
            position={[-38.201, -15.075, -66.619]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8393.869}
          />
          <instances.PolySurfaceweelr1
            position={[-182.329, -15.075, -66.619]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8393.869}
          />
          <instances.PCubeunderthecarbox
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PCylinderundercarwwe
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PastedpolySurfaceCarPaint
            position={[91.645, 112.864, 36.692]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1463.599}
          />
          <instances.PastedpolySurfaceCarPaint1
            position={[-88.799, 112.864, 36.692]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[-1463.599, 1463.599, 1463.599]}
          />
          <instances.PCubeinteriorcovergrill
            position={[56.913, 53.037, 186.654]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[4504.767, 6112.408, 2401.236]}
          />
          <instances.PCubeinteriorcovergrill1
            position={[-57.307, 53.037, 191.313]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[4504.767, 6112.408, 2401.236]}
          />
          <instances.PolySurfacelogo
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo1
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo2
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo3
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo4
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo5
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo6
            position={[1.253, -0.43, 211.811]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo7
            position={[1.332, -0.43, -324.41]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo8
            position={[0.847, -0.43, 19.023]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={6112.408}
          />
          <instances.PolySurfacelogo9
            position={[0.847, -0.43, 341.007]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={6112.408}
          />
          <instances.PolySurfaceStainlessSteel27
            position={[1.332, -17.76, 5.229]}
            rotation={[-1.642, 0, 0]}
            scale={[6112.408, 6112.407, 6112.407]}
          />
          <instances.PCubephong
            position={[1.332, -0.43, -2.401]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={6112.408}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rolls.glb')
